camel.karavan.projectId=arasodoo
camel.karavan.projectName=aras to odoo
camel.jbang.gav=org.camel.karavan.demo:arasodoo:1
camel.jbang.runtime=camel-main
camel.jbang.version=4.14.2
camel.jbang.dependencies=camel-console,camel-platform-http-main,org.apache.camel:camel-jacksonxml
camel.jbang.jib-maven-plugin-version=3.4.4
camel.server.enabled=true
camel.server.healthCheckEnabled=true
camel.server.devConsoleEnabled=true
camel.main.name=arasodoo
camel.main.tracingStandby=true
camel.trace.enabled=true
camel.main.autoConfigurationFailFast=false
camel.routecontroller.superviseEnabled=true
camel.routecontroller.backoffDelay=5000
camel.routecontroller.backoffMaxAttempts=100
camel.routecontroller.initialDelay=1000
camel.routecontroller.threadPoolSize=3
camel.context.dev-console=true
camel.health.enabled=true
camel.health.exposure-level=full
jkube.version=1.18.1
jib.from.image=gcr.io/distroless/java17@sha256:68e2373f7bef9486c08356bd9ffd3b40b56e6b9316c5f6885eb58b1d9093b43d
camel.component.jms.username=artemis
camel.component.jms.password=artemis
camel.main.dependency-download-enabled=true
camel.main.dependencies=org.apache.camel:camel-jacksonxml

# ---- Artemis queues ----
artemis.broker.url=tcp://artemis:61616
artemis.queue.aras.part=ArasPart
artemis.queue.odoo.part=ClassPart
artemis.queue.odoo.retry=ClassPartRetry

# ---- Odoo connection ----
odoo.jsonrpc=http://odoo:8069/jsonrpc
odoo.db=integration
odoo.user=2
odoo.pass=e00d153fc285e58c81b9e105dacfa2f0c61b3208
